<?php /* Smarty version 2.6.0, created on 2011-01-27 12:23:07
         compiled from blank.tpl */ ?>
<h1><?php echo $this->_tpl_vars['maintitle']; ?>
</h1>

<p>Welcome to Package <?php echo $this->_tpl_vars['package']; ?>
</p>

<p class="aside">
    This documentation was generated by 
    <a href="<?php echo $this->_tpl_vars['phpdocwebsite']; ?>
">phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
</a>
</p>